# Exceptions

Sadly, things often go wrong and our code needs to handle these exceptional situations.

We are now dealing with `addString` functions that occasionally throw an error:

```js
function addStringCallback (previous, current, callback) {
  setTimeout(() => {
    if (Math.random() > 0.8) {
      callback(new Error('cb bang!'))
    } else {
      callback(null, previous + ' ' + current)
    }
  }, Math.floor(Math.random() * 100))
}

function addStringPromise (previous, current) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (Math.random() > 0.8) {
        reject(new Error('bang!'))
      }
      resolve(previous + ' ' + current)
    }, Math.floor(Math.random() * 100))
  })
}
```

Notice how the callback convention is to pass two items to the function, the first is if there is an error, the second (and any other additional items) are the returned values.

## Exercise

Copy your functions from exercise 6 and update them to handle these exceptions.

If an error occurs we want to print 'whoops!' to the console.

## Extra Credit

If you get this far take turns to explain one of these topics in your group (take turns - 45 seconds each)

- How the event loop works in Javascript
- Why you want to use Async/Await over Promises or callbacks

ðŸ˜´ After that take a well deserved break.
